[Definition]
 
badagents = 360Spider|ZmEu|Auto Spider 1.0|zgrab|Wget\(.*\)|MauiBot.*|AspiegelBot.*|SemrushBot.*|PHP/.*|Go-http-client|python-requests|aiohttp|Scrapy|curl/|HeadlessChrome|Bytespider|libredtail|FreePBX-Scanner
 
failregex = ^<HOST> -.*"(GET|POST|HEAD).*HTTP.*(?:%(badagents)s)"$
            ^<HOST> - - \[.*\] \"\\n\" .*$
            ^<HOST> -.*"(GET|POST|HEAD) /*[pP][hH][pP][mM][yY][aA][dD][mM][iI][nN].*$
            ^<HOST> -.*"(GET|POST|HEAD) /+wp-login\.php.*$
            ^<HOST> -.*"(GET|POST|HEAD) /.git/.*$
            ^<HOST> -.*"(GET|POST|HEAD) /TP/public/index\.php.*$
            ^<HOST> -.*"(GET|POST|HEAD) /admin/login\.php.*$
            ^<HOST> -.*"(GET|POST|HEAD) /allstat\.php.*$
            ^<HOST> -.*"(GET|POST|HEAD) /cfg/.*$
            ^<HOST> -.*"(GET|POST|HEAD) /cisco/.*$
            ^<HOST> -.*"(GET|POST|HEAD) /config.*/.*$
            ^<HOST> -.*"(GET|POST|HEAD) /firmware/.*$
            ^<HOST> -.*"(GET|POST|HEAD) /linksys/.*$
            ^<HOST> -.*"(GET|POST|HEAD) /login\.cgi.*$
            ^<HOST> -.*"(GET|POST|HEAD) /phone/.*$
            ^<HOST> -.*"(GET|POST|HEAD) /polycom/.*$
            ^<HOST> -.*"(GET|POST|HEAD) /provision.*/.*$
            ^<HOST> -.*"(GET|POST|HEAD) /run\.py.*$
            ^<HOST> -.*"(GET|POST|HEAD) /struts.*$
            ^<HOST> -.*"(GET|POST|HEAD) /wls-wsat.*$
            ^<HOST> -.*"(GET|POST|HEAD) /wp-config\.php.*$
            ^<HOST> -.*"(GET|POST|HEAD) /wuwu11\.php.*$
            ^<HOST> -.*"(GET|POST|HEAD) /wwwroot\.rar.*$
            ^<HOST> -.*"(GET|POST|HEAD) http:.*/[pP][hH][pP][mM][yY][aA][dD][mM][iI][nN].*$
            ^<HOST> -.*"POST /rpc/trackback/.*$
            ^<HOST> -.*"(GET|POST|HEAD) /+pma(/|$).*$
            ^<HOST> -.*"(GET|POST|HEAD) /+typo3(/|$).*$
            ^<HOST> -.*"(GET|POST|HEAD) /+xampp(/|$).*$
            ^<HOST> -.*"(GET|POST|HEAD) /+wp-signup\.php.*$
            ^<HOST> -.*"(GET|POST|HEAD) /+wp-admin(/|$).*$
            ^<HOST> -.*"(GET|POST|HEAD) /+roundcube(/|$).*$
            ^<HOST> -.*"(GET|POST|HEAD) /.*\.env($| |\.).*$
            ^<HOST> -.*"(GET|POST|HEAD) /+wp-includes/.*$
            ^<HOST> -.*"(GET|POST|HEAD) /+xmlrpc\.php.*$
            ^<HOST> -.*"(GET|POST|HEAD) /+sftp-config\.json.*$
            ^<HOST> -.*"(GET|POST|HEAD) /+\.vscode/.*$
            ^<HOST> -.*"(GET|POST|HEAD) /.*wp.filemanager\.php.*$

ignoreregex =
