[INCLUDES]
before = apache-common.conf
 
[Definition]
failregex = (?i)^%(_apache_error_client)s (AH\d+:)? File does not exist: (?=.*(phpmyadmin|pma|admin|typo3|xampp|wp-(login|signup|admin)\.php|roundcube|sql|db)).*$
 
ignoreregex =
