export const faCalendarAlt: IconDefinition;
export const faCar: IconDefinition;
export const faCheck: IconDefinition;
export const faClock: IconDefinition;
export const faDoorOpen: IconDefinition;
export const faEnvelope: IconDefinition;
export const faEnvelopeOpen: IconDefinition;
export const faHome: IconDefinition;
export const faLockAlt: IconDefinition;
export const faMapMarkerAlt: IconDefinition;
export const faMinus: IconDefinition;
export const faMoon: IconDefinition;
export const faNotesMedical: IconDefinition;
export const faParking: IconDefinition;
export const faPhone: IconDefinition;
export const faPlus: IconDefinition;
export const faPlusCircle: IconDefinition;
export const faQuestionCircle: IconDefinition;
export const faSun: IconDefinition;
export const faTimes: IconDefinition;
export const faUser: IconDefinition;
export const faUsers: IconDefinition;
import { IconDefinition, IconLookup, IconName, IconPrefix, IconPack } from '@fortawesome/fontawesome-common-types';
export { IconDefinition, IconLookup, IconName, IconPrefix, IconPack } from '@fortawesome/fontawesome-common-types';
export const prefix: IconPrefix;
export const fal: IconPack;